[package]
name = "Agent"
version = "0.1.0"
edition = "2024"

[dependencies]
twox-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hmac = "0.13.0-pre.5"
sha2 = "0.11.0-pre.5"
hex = "0.4.3"
toml = "0.8.20"