// This file is @generated by prost-build.
/// Unified event wrapper for all event types.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(oneof = "event::Kind", tags = "1, 2, 3, 4, 5")]
    pub kind: ::core::option::Option<event::Kind>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// Events from hook module
        #[prost(message, tag = "1")]
        Hook(super::super::hook::HookEvent),
        /// Events from scanner module
        #[prost(message, tag = "2")]
        Scanner(super::super::scanner::FileScannerEvent),
        /// Events from callbacks: process creation
        #[prost(message, tag = "3")]
        ProcessEvent(super::super::callbacks::ProcessEvent),
        /// Events from callbacks: image load
        #[prost(message, tag = "4")]
        ImageLoad(super::super::callbacks::ImageLoadEvent),
        /// Events from callbacks: registry modifications
        #[prost(message, tag = "5")]
        Registry(super::super::callbacks::RegistryEvent),
    }
}
