name: "Tarjeta de desarrollo - Nueva funcionalidad"
description: "Crear una tarjeta para planificar e implementar una nueva funcionalidad del proyecto"
title: "[Feature] Nombre de la funcionalidad"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        З **Nueva funcionalidad**

        Completa esta tarjeta para documentar una nueva tarea de desarrollo o implementaci贸n.

  - type: input
    id: feature_name
    attributes:
      label: "Nombre de la funcionalidad"
      description: "Breve nombre identificativo de la tarea o funcionalidad."
      placeholder: "Ejemplo: Autenticaci贸n con JWT"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripci贸n t茅cnica"
      description: "Explica brevemente qu茅 se debe desarrollar. Se recomienda indicar m贸dulos o componentes afectados."
      placeholder: "Ejemplo: Implementar el m贸dulo de autenticaci贸n basado en JWT. Incluir endpoints de login, logout y verificaci贸n de token."
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "Objetivo o resultado esperado"
      description: "Indica qu茅 se busca conseguir con esta funcionalidad o cu谩l es el valor que aporta al sistema."
      placeholder: "Ejemplo: Permitir la autenticaci贸n sin mantener sesiones en el servidor, facilitando la escalabilidad del backend."
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: "Detalles de implementaci贸n"
      description: "A帽ade informaci贸n t茅cnica relevante sobre c贸mo deber铆a implementarse. Puedes incluir librer铆as, endpoints, estructuras de datos o esquemas."
      placeholder: "Ejemplo: Usar la librer铆a jsonwebtoken. Crear middleware de validaci贸n de token en las rutas protegidas."
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Criterios de aceptaci贸n"
      description: "Define las condiciones m铆nimas que deben cumplirse para dar la funcionalidad por completada."
      placeholder: |
        - El usuario puede iniciar sesi贸n correctamente.
        - Se devuelve un JWT v谩lido.
        - Las rutas protegidas solo permiten acceso con token v谩lido.
        - Se a帽aden pruebas unitarias.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencias o relaciones"
      description: "Indica si esta tarea depende de otra o afecta a otras partes del proyecto."
      placeholder: "Ejemplo: Depende de la finalizaci贸n del issue #42 (registro de usuario)."
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Notas adicionales"
      description: "A帽ade informaci贸n complementaria, referencias o enlaces a documentaci贸n."
      placeholder: "Ejemplo: Referencia JWT RFC 7519 - https://www.rfc-editor.org/rfc/rfc7519"
    validations:
      required: false
